[book]
authors = []
language = "en"
multilingual = false
src = "src"
title = "Nois Network"

[output.html]
git-repository-url = "https://github.com/noislabs/whitepaper"
edit-url-template = "https://github.com/noislabs/whitepaper/edit/main/{path}"
